project:
  type: website
  output-dir: docs

website:
  title: "PM 566 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: PM566_Midterm.qmd
        text: LA Galaxy 2022-2023 Season

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

