project:
  type: website
  output-dir: docs

website:
  title: "PM 566 Final Project"
  navbar:
    left:
      - href: PM566_Midterm.html
        text: Home
      - href: index.qmd
        text: Report Download

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

